### ISSUE TITLE
xtend documentation: inline code rendered incorrectly

### ISSUE THREAD

**Issue by Treverix** [eclipse/xtext#1091]
Random url that shows the problem:

http://www.eclipse.org/xtend/documentation/202_xtend_classes_members.html#package-decl

The `^` is not rendered as inlined code but as a table.

**Comment by cdietrich** [comment]
see https://github.com/eclipse/xtext-xtend/issues/104 as well

**Comment by cdietrich** [comment]
fixed with xtext 2.11

**Comment by EricSalemi** [comment]
Problem is still visible on link originally reported by Treverix.

**Comment by cdietrich** [comment]
<img width="709" alt="bildschirmfoto 2017-01-13 um 15 42 41" src="https://cloud.githubusercontent.com/assets/238736/21933772/fbb1e522-d9a6-11e6-8eae-c835d8b8019d.png">

**Comment by cdietrich** [comment]
this is not yet live, it will be with 2.11

**Comment by cdietrich** [comment]
@Treverix @EricSalemi  fix is "live" now

**Comment by Treverix** [comment]
Your're great! And I'm looking forward to 2.11!!
